// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/LocalVolatility.h"
#include <Rcpp.h>
#include <string>
#include <set>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// american_option_2d
double american_option_2d(double s_0, double x_0, double k, double tau, double r_d, double r_f, double q, double sigma_s, double sigma_x, double rho, String type, double s_min, double s_max, double x_min, double x_max, int n_s, int n_x, int n_t, double alpha, double lambda, double tolerance);
static SEXP _LocalVolatility_american_option_2d_try(SEXP s_0SEXP, SEXP x_0SEXP, SEXP kSEXP, SEXP tauSEXP, SEXP r_dSEXP, SEXP r_fSEXP, SEXP qSEXP, SEXP sigma_sSEXP, SEXP sigma_xSEXP, SEXP rhoSEXP, SEXP typeSEXP, SEXP s_minSEXP, SEXP s_maxSEXP, SEXP x_minSEXP, SEXP x_maxSEXP, SEXP n_sSEXP, SEXP n_xSEXP, SEXP n_tSEXP, SEXP alphaSEXP, SEXP lambdaSEXP, SEXP toleranceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< double >::type s_0(s_0SEXP);
    Rcpp::traits::input_parameter< double >::type x_0(x_0SEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< double >::type r_d(r_dSEXP);
    Rcpp::traits::input_parameter< double >::type r_f(r_fSEXP);
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_s(sigma_sSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_x(sigma_xSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< String >::type type(typeSEXP);
    Rcpp::traits::input_parameter< double >::type s_min(s_minSEXP);
    Rcpp::traits::input_parameter< double >::type s_max(s_maxSEXP);
    Rcpp::traits::input_parameter< double >::type x_min(x_minSEXP);
    Rcpp::traits::input_parameter< double >::type x_max(x_maxSEXP);
    Rcpp::traits::input_parameter< int >::type n_s(n_sSEXP);
    Rcpp::traits::input_parameter< int >::type n_x(n_xSEXP);
    Rcpp::traits::input_parameter< int >::type n_t(n_tSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type tolerance(toleranceSEXP);
    rcpp_result_gen = Rcpp::wrap(american_option_2d(s_0, x_0, k, tau, r_d, r_f, q, sigma_s, sigma_x, rho, type, s_min, s_max, x_min, x_max, n_s, n_x, n_t, alpha, lambda, tolerance));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _LocalVolatility_american_option_2d(SEXP s_0SEXP, SEXP x_0SEXP, SEXP kSEXP, SEXP tauSEXP, SEXP r_dSEXP, SEXP r_fSEXP, SEXP qSEXP, SEXP sigma_sSEXP, SEXP sigma_xSEXP, SEXP rhoSEXP, SEXP typeSEXP, SEXP s_minSEXP, SEXP s_maxSEXP, SEXP x_minSEXP, SEXP x_maxSEXP, SEXP n_sSEXP, SEXP n_xSEXP, SEXP n_tSEXP, SEXP alphaSEXP, SEXP lambdaSEXP, SEXP toleranceSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_LocalVolatility_american_option_2d_try(s_0SEXP, x_0SEXP, kSEXP, tauSEXP, r_dSEXP, r_fSEXP, qSEXP, sigma_sSEXP, sigma_xSEXP, rhoSEXP, typeSEXP, s_minSEXP, s_maxSEXP, x_minSEXP, x_maxSEXP, n_sSEXP, n_xSEXP, n_tSEXP, alphaSEXP, lambdaSEXP, toleranceSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        (Rf_error)("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// american_option_heston
double american_option_heston(double s_0, double k, double tau, double r_d, double q, double kappa, double theta, double xi, double rho, double v_0, String type, double s_min, double s_max, double v_min, double v_max, int n_s, int n_v, int n_t, double alpha, double lambda, double tolerance);
static SEXP _LocalVolatility_american_option_heston_try(SEXP s_0SEXP, SEXP kSEXP, SEXP tauSEXP, SEXP r_dSEXP, SEXP qSEXP, SEXP kappaSEXP, SEXP thetaSEXP, SEXP xiSEXP, SEXP rhoSEXP, SEXP v_0SEXP, SEXP typeSEXP, SEXP s_minSEXP, SEXP s_maxSEXP, SEXP v_minSEXP, SEXP v_maxSEXP, SEXP n_sSEXP, SEXP n_vSEXP, SEXP n_tSEXP, SEXP alphaSEXP, SEXP lambdaSEXP, SEXP toleranceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< double >::type s_0(s_0SEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< double >::type r_d(r_dSEXP);
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type kappa(kappaSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type v_0(v_0SEXP);
    Rcpp::traits::input_parameter< String >::type type(typeSEXP);
    Rcpp::traits::input_parameter< double >::type s_min(s_minSEXP);
    Rcpp::traits::input_parameter< double >::type s_max(s_maxSEXP);
    Rcpp::traits::input_parameter< double >::type v_min(v_minSEXP);
    Rcpp::traits::input_parameter< double >::type v_max(v_maxSEXP);
    Rcpp::traits::input_parameter< int >::type n_s(n_sSEXP);
    Rcpp::traits::input_parameter< int >::type n_v(n_vSEXP);
    Rcpp::traits::input_parameter< int >::type n_t(n_tSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type tolerance(toleranceSEXP);
    rcpp_result_gen = Rcpp::wrap(american_option_heston(s_0, k, tau, r_d, q, kappa, theta, xi, rho, v_0, type, s_min, s_max, v_min, v_max, n_s, n_v, n_t, alpha, lambda, tolerance));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _LocalVolatility_american_option_heston(SEXP s_0SEXP, SEXP kSEXP, SEXP tauSEXP, SEXP r_dSEXP, SEXP qSEXP, SEXP kappaSEXP, SEXP thetaSEXP, SEXP xiSEXP, SEXP rhoSEXP, SEXP v_0SEXP, SEXP typeSEXP, SEXP s_minSEXP, SEXP s_maxSEXP, SEXP v_minSEXP, SEXP v_maxSEXP, SEXP n_sSEXP, SEXP n_vSEXP, SEXP n_tSEXP, SEXP alphaSEXP, SEXP lambdaSEXP, SEXP toleranceSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_LocalVolatility_american_option_heston_try(s_0SEXP, kSEXP, tauSEXP, r_dSEXP, qSEXP, kappaSEXP, thetaSEXP, xiSEXP, rhoSEXP, v_0SEXP, typeSEXP, s_minSEXP, s_maxSEXP, v_minSEXP, v_maxSEXP, n_sSEXP, n_vSEXP, n_tSEXP, alphaSEXP, lambdaSEXP, toleranceSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        (Rf_error)("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// american_option_lv
double american_option_lv(double s_0, double k, double tau, double r_d, double r_f, NumericMatrix sigma, String type, double s_min, double s_max, int n_s, int n_t, double lambda, double tolerance);
static SEXP _LocalVolatility_american_option_lv_try(SEXP s_0SEXP, SEXP kSEXP, SEXP tauSEXP, SEXP r_dSEXP, SEXP r_fSEXP, SEXP sigmaSEXP, SEXP typeSEXP, SEXP s_minSEXP, SEXP s_maxSEXP, SEXP n_sSEXP, SEXP n_tSEXP, SEXP lambdaSEXP, SEXP toleranceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< double >::type s_0(s_0SEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< double >::type r_d(r_dSEXP);
    Rcpp::traits::input_parameter< double >::type r_f(r_fSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< String >::type type(typeSEXP);
    Rcpp::traits::input_parameter< double >::type s_min(s_minSEXP);
    Rcpp::traits::input_parameter< double >::type s_max(s_maxSEXP);
    Rcpp::traits::input_parameter< int >::type n_s(n_sSEXP);
    Rcpp::traits::input_parameter< int >::type n_t(n_tSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type tolerance(toleranceSEXP);
    rcpp_result_gen = Rcpp::wrap(american_option_lv(s_0, k, tau, r_d, r_f, sigma, type, s_min, s_max, n_s, n_t, lambda, tolerance));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _LocalVolatility_american_option_lv(SEXP s_0SEXP, SEXP kSEXP, SEXP tauSEXP, SEXP r_dSEXP, SEXP r_fSEXP, SEXP sigmaSEXP, SEXP typeSEXP, SEXP s_minSEXP, SEXP s_maxSEXP, SEXP n_sSEXP, SEXP n_tSEXP, SEXP lambdaSEXP, SEXP toleranceSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_LocalVolatility_american_option_lv_try(s_0SEXP, kSEXP, tauSEXP, r_dSEXP, r_fSEXP, sigmaSEXP, typeSEXP, s_minSEXP, s_maxSEXP, n_sSEXP, n_tSEXP, lambdaSEXP, toleranceSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        (Rf_error)("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// american_option_lv_2d
double american_option_lv_2d(double s_0, double x_0, double k, double tau, double r_d, double r_f, double q, NumericMatrix sigma_s, NumericMatrix sigma_x, double rho, String type, double s_min, double s_max, double x_min, double x_max, int n_s, int n_x, int n_t, double alpha, double lambda, double tolerance);
static SEXP _LocalVolatility_american_option_lv_2d_try(SEXP s_0SEXP, SEXP x_0SEXP, SEXP kSEXP, SEXP tauSEXP, SEXP r_dSEXP, SEXP r_fSEXP, SEXP qSEXP, SEXP sigma_sSEXP, SEXP sigma_xSEXP, SEXP rhoSEXP, SEXP typeSEXP, SEXP s_minSEXP, SEXP s_maxSEXP, SEXP x_minSEXP, SEXP x_maxSEXP, SEXP n_sSEXP, SEXP n_xSEXP, SEXP n_tSEXP, SEXP alphaSEXP, SEXP lambdaSEXP, SEXP toleranceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< double >::type s_0(s_0SEXP);
    Rcpp::traits::input_parameter< double >::type x_0(x_0SEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< double >::type r_d(r_dSEXP);
    Rcpp::traits::input_parameter< double >::type r_f(r_fSEXP);
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type sigma_s(sigma_sSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type sigma_x(sigma_xSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< String >::type type(typeSEXP);
    Rcpp::traits::input_parameter< double >::type s_min(s_minSEXP);
    Rcpp::traits::input_parameter< double >::type s_max(s_maxSEXP);
    Rcpp::traits::input_parameter< double >::type x_min(x_minSEXP);
    Rcpp::traits::input_parameter< double >::type x_max(x_maxSEXP);
    Rcpp::traits::input_parameter< int >::type n_s(n_sSEXP);
    Rcpp::traits::input_parameter< int >::type n_x(n_xSEXP);
    Rcpp::traits::input_parameter< int >::type n_t(n_tSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type tolerance(toleranceSEXP);
    rcpp_result_gen = Rcpp::wrap(american_option_lv_2d(s_0, x_0, k, tau, r_d, r_f, q, sigma_s, sigma_x, rho, type, s_min, s_max, x_min, x_max, n_s, n_x, n_t, alpha, lambda, tolerance));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _LocalVolatility_american_option_lv_2d(SEXP s_0SEXP, SEXP x_0SEXP, SEXP kSEXP, SEXP tauSEXP, SEXP r_dSEXP, SEXP r_fSEXP, SEXP qSEXP, SEXP sigma_sSEXP, SEXP sigma_xSEXP, SEXP rhoSEXP, SEXP typeSEXP, SEXP s_minSEXP, SEXP s_maxSEXP, SEXP x_minSEXP, SEXP x_maxSEXP, SEXP n_sSEXP, SEXP n_xSEXP, SEXP n_tSEXP, SEXP alphaSEXP, SEXP lambdaSEXP, SEXP toleranceSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_LocalVolatility_american_option_lv_2d_try(s_0SEXP, x_0SEXP, kSEXP, tauSEXP, r_dSEXP, r_fSEXP, qSEXP, sigma_sSEXP, sigma_xSEXP, rhoSEXP, typeSEXP, s_minSEXP, s_maxSEXP, x_minSEXP, x_maxSEXP, n_sSEXP, n_xSEXP, n_tSEXP, alphaSEXP, lambdaSEXP, toleranceSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        (Rf_error)("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// batch_price_european_lv
Rcpp::NumericVector batch_price_european_lv(const Rcpp::NumericVector& spots, const Rcpp::NumericVector& strikes, const Rcpp::NumericVector& taus, const Rcpp::NumericVector& r_ds, const Rcpp::NumericVector& r_fs, const Rcpp::NumericMatrix& sigma, const Rcpp::StringVector& types, double s_min, double s_max, int n_s, int n_t);
static SEXP _LocalVolatility_batch_price_european_lv_try(SEXP spotsSEXP, SEXP strikesSEXP, SEXP tausSEXP, SEXP r_dsSEXP, SEXP r_fsSEXP, SEXP sigmaSEXP, SEXP typesSEXP, SEXP s_minSEXP, SEXP s_maxSEXP, SEXP n_sSEXP, SEXP n_tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type spots(spotsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type strikes(strikesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type taus(tausSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type r_ds(r_dsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type r_fs(r_fsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::StringVector& >::type types(typesSEXP);
    Rcpp::traits::input_parameter< double >::type s_min(s_minSEXP);
    Rcpp::traits::input_parameter< double >::type s_max(s_maxSEXP);
    Rcpp::traits::input_parameter< int >::type n_s(n_sSEXP);
    Rcpp::traits::input_parameter< int >::type n_t(n_tSEXP);
    rcpp_result_gen = Rcpp::wrap(batch_price_european_lv(spots, strikes, taus, r_ds, r_fs, sigma, types, s_min, s_max, n_s, n_t));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _LocalVolatility_batch_price_european_lv(SEXP spotsSEXP, SEXP strikesSEXP, SEXP tausSEXP, SEXP r_dsSEXP, SEXP r_fsSEXP, SEXP sigmaSEXP, SEXP typesSEXP, SEXP s_minSEXP, SEXP s_maxSEXP, SEXP n_sSEXP, SEXP n_tSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_LocalVolatility_batch_price_european_lv_try(spotsSEXP, strikesSEXP, tausSEXP, r_dsSEXP, r_fsSEXP, sigmaSEXP, typesSEXP, s_minSEXP, s_maxSEXP, n_sSEXP, n_tSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        (Rf_error)("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// batch_price_american_lv
Rcpp::NumericVector batch_price_american_lv(const Rcpp::NumericVector& spots, const Rcpp::NumericVector& strikes, const Rcpp::NumericVector& taus, const Rcpp::NumericVector& r_ds, const Rcpp::NumericVector& r_fs, const Rcpp::NumericMatrix& sigma, const Rcpp::StringVector& types, double s_min, double s_max, int n_s, int n_t, double lambda, double tolerance, int n_threads);
static SEXP _LocalVolatility_batch_price_american_lv_try(SEXP spotsSEXP, SEXP strikesSEXP, SEXP tausSEXP, SEXP r_dsSEXP, SEXP r_fsSEXP, SEXP sigmaSEXP, SEXP typesSEXP, SEXP s_minSEXP, SEXP s_maxSEXP, SEXP n_sSEXP, SEXP n_tSEXP, SEXP lambdaSEXP, SEXP toleranceSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type spots(spotsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type strikes(strikesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type taus(tausSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type r_ds(r_dsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type r_fs(r_fsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::StringVector& >::type types(typesSEXP);
    Rcpp::traits::input_parameter< double >::type s_min(s_minSEXP);
    Rcpp::traits::input_parameter< double >::type s_max(s_maxSEXP);
    Rcpp::traits::input_parameter< int >::type n_s(n_sSEXP);
    Rcpp::traits::input_parameter< int >::type n_t(n_tSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type tolerance(toleranceSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(batch_price_american_lv(spots, strikes, taus, r_ds, r_fs, sigma, types, s_min, s_max, n_s, n_t, lambda, tolerance, n_threads));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _LocalVolatility_batch_price_american_lv(SEXP spotsSEXP, SEXP strikesSEXP, SEXP tausSEXP, SEXP r_dsSEXP, SEXP r_fsSEXP, SEXP sigmaSEXP, SEXP typesSEXP, SEXP s_minSEXP, SEXP s_maxSEXP, SEXP n_sSEXP, SEXP n_tSEXP, SEXP lambdaSEXP, SEXP toleranceSEXP, SEXP n_threadsSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_LocalVolatility_batch_price_american_lv_try(spotsSEXP, strikesSEXP, tausSEXP, r_dsSEXP, r_fsSEXP, sigmaSEXP, typesSEXP, s_minSEXP, s_maxSEXP, n_sSEXP, n_tSEXP, lambdaSEXP, toleranceSEXP, n_threadsSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        (Rf_error)("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// european_option_2d
double european_option_2d(double s_0, double x_0, double k, double tau, double r_d, double r_f, double q, double sigma_s, double sigma_x, double rho, String type, double s_min, double s_max, double x_min, double x_max, int n_s, int n_x, int n_t, double alpha);
static SEXP _LocalVolatility_european_option_2d_try(SEXP s_0SEXP, SEXP x_0SEXP, SEXP kSEXP, SEXP tauSEXP, SEXP r_dSEXP, SEXP r_fSEXP, SEXP qSEXP, SEXP sigma_sSEXP, SEXP sigma_xSEXP, SEXP rhoSEXP, SEXP typeSEXP, SEXP s_minSEXP, SEXP s_maxSEXP, SEXP x_minSEXP, SEXP x_maxSEXP, SEXP n_sSEXP, SEXP n_xSEXP, SEXP n_tSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< double >::type s_0(s_0SEXP);
    Rcpp::traits::input_parameter< double >::type x_0(x_0SEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< double >::type r_d(r_dSEXP);
    Rcpp::traits::input_parameter< double >::type r_f(r_fSEXP);
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_s(sigma_sSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_x(sigma_xSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< String >::type type(typeSEXP);
    Rcpp::traits::input_parameter< double >::type s_min(s_minSEXP);
    Rcpp::traits::input_parameter< double >::type s_max(s_maxSEXP);
    Rcpp::traits::input_parameter< double >::type x_min(x_minSEXP);
    Rcpp::traits::input_parameter< double >::type x_max(x_maxSEXP);
    Rcpp::traits::input_parameter< int >::type n_s(n_sSEXP);
    Rcpp::traits::input_parameter< int >::type n_x(n_xSEXP);
    Rcpp::traits::input_parameter< int >::type n_t(n_tSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(european_option_2d(s_0, x_0, k, tau, r_d, r_f, q, sigma_s, sigma_x, rho, type, s_min, s_max, x_min, x_max, n_s, n_x, n_t, alpha));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _LocalVolatility_european_option_2d(SEXP s_0SEXP, SEXP x_0SEXP, SEXP kSEXP, SEXP tauSEXP, SEXP r_dSEXP, SEXP r_fSEXP, SEXP qSEXP, SEXP sigma_sSEXP, SEXP sigma_xSEXP, SEXP rhoSEXP, SEXP typeSEXP, SEXP s_minSEXP, SEXP s_maxSEXP, SEXP x_minSEXP, SEXP x_maxSEXP, SEXP n_sSEXP, SEXP n_xSEXP, SEXP n_tSEXP, SEXP alphaSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_LocalVolatility_european_option_2d_try(s_0SEXP, x_0SEXP, kSEXP, tauSEXP, r_dSEXP, r_fSEXP, qSEXP, sigma_sSEXP, sigma_xSEXP, rhoSEXP, typeSEXP, s_minSEXP, s_maxSEXP, x_minSEXP, x_maxSEXP, n_sSEXP, n_xSEXP, n_tSEXP, alphaSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        (Rf_error)("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// european_option_cf_2d
double european_option_cf_2d(double s_0, double x_0, double k, double tau, double r_d, double r_f, double q, double sigma_s, double sigma_x, double rho, String type, int adr_ratio);
static SEXP _LocalVolatility_european_option_cf_2d_try(SEXP s_0SEXP, SEXP x_0SEXP, SEXP kSEXP, SEXP tauSEXP, SEXP r_dSEXP, SEXP r_fSEXP, SEXP qSEXP, SEXP sigma_sSEXP, SEXP sigma_xSEXP, SEXP rhoSEXP, SEXP typeSEXP, SEXP adr_ratioSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< double >::type s_0(s_0SEXP);
    Rcpp::traits::input_parameter< double >::type x_0(x_0SEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< double >::type r_d(r_dSEXP);
    Rcpp::traits::input_parameter< double >::type r_f(r_fSEXP);
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_s(sigma_sSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_x(sigma_xSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< String >::type type(typeSEXP);
    Rcpp::traits::input_parameter< int >::type adr_ratio(adr_ratioSEXP);
    rcpp_result_gen = Rcpp::wrap(european_option_cf_2d(s_0, x_0, k, tau, r_d, r_f, q, sigma_s, sigma_x, rho, type, adr_ratio));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _LocalVolatility_european_option_cf_2d(SEXP s_0SEXP, SEXP x_0SEXP, SEXP kSEXP, SEXP tauSEXP, SEXP r_dSEXP, SEXP r_fSEXP, SEXP qSEXP, SEXP sigma_sSEXP, SEXP sigma_xSEXP, SEXP rhoSEXP, SEXP typeSEXP, SEXP adr_ratioSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_LocalVolatility_european_option_cf_2d_try(s_0SEXP, x_0SEXP, kSEXP, tauSEXP, r_dSEXP, r_fSEXP, qSEXP, sigma_sSEXP, sigma_xSEXP, rhoSEXP, typeSEXP, adr_ratioSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        (Rf_error)("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// european_option_heston
double european_option_heston(double s_0, double k, double tau, double r_d, double q, double kappa, double theta, double xi, double rho, double v_0, String type, double s_min, double s_max, double v_min, double v_max, int n_s, int n_v, int n_t, double alpha);
static SEXP _LocalVolatility_european_option_heston_try(SEXP s_0SEXP, SEXP kSEXP, SEXP tauSEXP, SEXP r_dSEXP, SEXP qSEXP, SEXP kappaSEXP, SEXP thetaSEXP, SEXP xiSEXP, SEXP rhoSEXP, SEXP v_0SEXP, SEXP typeSEXP, SEXP s_minSEXP, SEXP s_maxSEXP, SEXP v_minSEXP, SEXP v_maxSEXP, SEXP n_sSEXP, SEXP n_vSEXP, SEXP n_tSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< double >::type s_0(s_0SEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< double >::type r_d(r_dSEXP);
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type kappa(kappaSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type v_0(v_0SEXP);
    Rcpp::traits::input_parameter< String >::type type(typeSEXP);
    Rcpp::traits::input_parameter< double >::type s_min(s_minSEXP);
    Rcpp::traits::input_parameter< double >::type s_max(s_maxSEXP);
    Rcpp::traits::input_parameter< double >::type v_min(v_minSEXP);
    Rcpp::traits::input_parameter< double >::type v_max(v_maxSEXP);
    Rcpp::traits::input_parameter< int >::type n_s(n_sSEXP);
    Rcpp::traits::input_parameter< int >::type n_v(n_vSEXP);
    Rcpp::traits::input_parameter< int >::type n_t(n_tSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(european_option_heston(s_0, k, tau, r_d, q, kappa, theta, xi, rho, v_0, type, s_min, s_max, v_min, v_max, n_s, n_v, n_t, alpha));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _LocalVolatility_european_option_heston(SEXP s_0SEXP, SEXP kSEXP, SEXP tauSEXP, SEXP r_dSEXP, SEXP qSEXP, SEXP kappaSEXP, SEXP thetaSEXP, SEXP xiSEXP, SEXP rhoSEXP, SEXP v_0SEXP, SEXP typeSEXP, SEXP s_minSEXP, SEXP s_maxSEXP, SEXP v_minSEXP, SEXP v_maxSEXP, SEXP n_sSEXP, SEXP n_vSEXP, SEXP n_tSEXP, SEXP alphaSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_LocalVolatility_european_option_heston_try(s_0SEXP, kSEXP, tauSEXP, r_dSEXP, qSEXP, kappaSEXP, thetaSEXP, xiSEXP, rhoSEXP, v_0SEXP, typeSEXP, s_minSEXP, s_maxSEXP, v_minSEXP, v_maxSEXP, n_sSEXP, n_vSEXP, n_tSEXP, alphaSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        (Rf_error)("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// european_option_lv
double european_option_lv(double s_0, double k, double tau, double r_d, double r_f, NumericMatrix sigma, String type, double s_min, double s_max, int n_s, int n_t);
static SEXP _LocalVolatility_european_option_lv_try(SEXP s_0SEXP, SEXP kSEXP, SEXP tauSEXP, SEXP r_dSEXP, SEXP r_fSEXP, SEXP sigmaSEXP, SEXP typeSEXP, SEXP s_minSEXP, SEXP s_maxSEXP, SEXP n_sSEXP, SEXP n_tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< double >::type s_0(s_0SEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< double >::type r_d(r_dSEXP);
    Rcpp::traits::input_parameter< double >::type r_f(r_fSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< String >::type type(typeSEXP);
    Rcpp::traits::input_parameter< double >::type s_min(s_minSEXP);
    Rcpp::traits::input_parameter< double >::type s_max(s_maxSEXP);
    Rcpp::traits::input_parameter< int >::type n_s(n_sSEXP);
    Rcpp::traits::input_parameter< int >::type n_t(n_tSEXP);
    rcpp_result_gen = Rcpp::wrap(european_option_lv(s_0, k, tau, r_d, r_f, sigma, type, s_min, s_max, n_s, n_t));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _LocalVolatility_european_option_lv(SEXP s_0SEXP, SEXP kSEXP, SEXP tauSEXP, SEXP r_dSEXP, SEXP r_fSEXP, SEXP sigmaSEXP, SEXP typeSEXP, SEXP s_minSEXP, SEXP s_maxSEXP, SEXP n_sSEXP, SEXP n_tSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_LocalVolatility_european_option_lv_try(s_0SEXP, kSEXP, tauSEXP, r_dSEXP, r_fSEXP, sigmaSEXP, typeSEXP, s_minSEXP, s_maxSEXP, n_sSEXP, n_tSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        (Rf_error)("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// european_option_lv_2d
double european_option_lv_2d(double s_0, double x_0, double k, double tau, double r_d, double r_f, double q, NumericMatrix sigma_s, NumericMatrix sigma_x, double rho, String type, double s_min, double s_max, double x_min, double x_max, int n_s, int n_x, int n_t, double alpha);
static SEXP _LocalVolatility_european_option_lv_2d_try(SEXP s_0SEXP, SEXP x_0SEXP, SEXP kSEXP, SEXP tauSEXP, SEXP r_dSEXP, SEXP r_fSEXP, SEXP qSEXP, SEXP sigma_sSEXP, SEXP sigma_xSEXP, SEXP rhoSEXP, SEXP typeSEXP, SEXP s_minSEXP, SEXP s_maxSEXP, SEXP x_minSEXP, SEXP x_maxSEXP, SEXP n_sSEXP, SEXP n_xSEXP, SEXP n_tSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< double >::type s_0(s_0SEXP);
    Rcpp::traits::input_parameter< double >::type x_0(x_0SEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< double >::type r_d(r_dSEXP);
    Rcpp::traits::input_parameter< double >::type r_f(r_fSEXP);
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type sigma_s(sigma_sSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type sigma_x(sigma_xSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< String >::type type(typeSEXP);
    Rcpp::traits::input_parameter< double >::type s_min(s_minSEXP);
    Rcpp::traits::input_parameter< double >::type s_max(s_maxSEXP);
    Rcpp::traits::input_parameter< double >::type x_min(x_minSEXP);
    Rcpp::traits::input_parameter< double >::type x_max(x_maxSEXP);
    Rcpp::traits::input_parameter< int >::type n_s(n_sSEXP);
    Rcpp::traits::input_parameter< int >::type n_x(n_xSEXP);
    Rcpp::traits::input_parameter< int >::type n_t(n_tSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(european_option_lv_2d(s_0, x_0, k, tau, r_d, r_f, q, sigma_s, sigma_x, rho, type, s_min, s_max, x_min, x_max, n_s, n_x, n_t, alpha));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _LocalVolatility_european_option_lv_2d(SEXP s_0SEXP, SEXP x_0SEXP, SEXP kSEXP, SEXP tauSEXP, SEXP r_dSEXP, SEXP r_fSEXP, SEXP qSEXP, SEXP sigma_sSEXP, SEXP sigma_xSEXP, SEXP rhoSEXP, SEXP typeSEXP, SEXP s_minSEXP, SEXP s_maxSEXP, SEXP x_minSEXP, SEXP x_maxSEXP, SEXP n_sSEXP, SEXP n_xSEXP, SEXP n_tSEXP, SEXP alphaSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_LocalVolatility_european_option_lv_2d_try(s_0SEXP, x_0SEXP, kSEXP, tauSEXP, r_dSEXP, r_fSEXP, qSEXP, sigma_sSEXP, sigma_xSEXP, rhoSEXP, typeSEXP, s_minSEXP, s_maxSEXP, x_minSEXP, x_maxSEXP, n_sSEXP, n_xSEXP, n_tSEXP, alphaSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        (Rf_error)("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// heston_cf
double heston_cf(double s_0, double k, double tau, double r_d, double q, double kappa, double theta, double xi, double rho, double v_0, String type);
static SEXP _LocalVolatility_heston_cf_try(SEXP s_0SEXP, SEXP kSEXP, SEXP tauSEXP, SEXP r_dSEXP, SEXP qSEXP, SEXP kappaSEXP, SEXP thetaSEXP, SEXP xiSEXP, SEXP rhoSEXP, SEXP v_0SEXP, SEXP typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< double >::type s_0(s_0SEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< double >::type r_d(r_dSEXP);
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type kappa(kappaSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type v_0(v_0SEXP);
    Rcpp::traits::input_parameter< String >::type type(typeSEXP);
    rcpp_result_gen = Rcpp::wrap(heston_cf(s_0, k, tau, r_d, q, kappa, theta, xi, rho, v_0, type));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _LocalVolatility_heston_cf(SEXP s_0SEXP, SEXP kSEXP, SEXP tauSEXP, SEXP r_dSEXP, SEXP qSEXP, SEXP kappaSEXP, SEXP thetaSEXP, SEXP xiSEXP, SEXP rhoSEXP, SEXP v_0SEXP, SEXP typeSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_LocalVolatility_heston_cf_try(s_0SEXP, kSEXP, tauSEXP, r_dSEXP, qSEXP, kappaSEXP, thetaSEXP, xiSEXP, rhoSEXP, v_0SEXP, typeSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        (Rf_error)("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// mc_american_heston_4d
Rcpp::List mc_american_heston_4d(double s_0, double x_0, double k, double tau, double r_d, double r_f, double q, double kappa_s, double theta_s, double xi_s, double v_s0, double kappa_x, double theta_x, double xi_x, double v_x0, double rho_sx, double rho_sv, double rho_xv, double rho_svx, double rho_xvs, double rho_vsvx, String type, int n_paths, int n_steps, int seed, int n_basis, int n_threads);
static SEXP _LocalVolatility_mc_american_heston_4d_try(SEXP s_0SEXP, SEXP x_0SEXP, SEXP kSEXP, SEXP tauSEXP, SEXP r_dSEXP, SEXP r_fSEXP, SEXP qSEXP, SEXP kappa_sSEXP, SEXP theta_sSEXP, SEXP xi_sSEXP, SEXP v_s0SEXP, SEXP kappa_xSEXP, SEXP theta_xSEXP, SEXP xi_xSEXP, SEXP v_x0SEXP, SEXP rho_sxSEXP, SEXP rho_svSEXP, SEXP rho_xvSEXP, SEXP rho_svxSEXP, SEXP rho_xvsSEXP, SEXP rho_vsvxSEXP, SEXP typeSEXP, SEXP n_pathsSEXP, SEXP n_stepsSEXP, SEXP seedSEXP, SEXP n_basisSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< double >::type s_0(s_0SEXP);
    Rcpp::traits::input_parameter< double >::type x_0(x_0SEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< double >::type r_d(r_dSEXP);
    Rcpp::traits::input_parameter< double >::type r_f(r_fSEXP);
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type kappa_s(kappa_sSEXP);
    Rcpp::traits::input_parameter< double >::type theta_s(theta_sSEXP);
    Rcpp::traits::input_parameter< double >::type xi_s(xi_sSEXP);
    Rcpp::traits::input_parameter< double >::type v_s0(v_s0SEXP);
    Rcpp::traits::input_parameter< double >::type kappa_x(kappa_xSEXP);
    Rcpp::traits::input_parameter< double >::type theta_x(theta_xSEXP);
    Rcpp::traits::input_parameter< double >::type xi_x(xi_xSEXP);
    Rcpp::traits::input_parameter< double >::type v_x0(v_x0SEXP);
    Rcpp::traits::input_parameter< double >::type rho_sx(rho_sxSEXP);
    Rcpp::traits::input_parameter< double >::type rho_sv(rho_svSEXP);
    Rcpp::traits::input_parameter< double >::type rho_xv(rho_xvSEXP);
    Rcpp::traits::input_parameter< double >::type rho_svx(rho_svxSEXP);
    Rcpp::traits::input_parameter< double >::type rho_xvs(rho_xvsSEXP);
    Rcpp::traits::input_parameter< double >::type rho_vsvx(rho_vsvxSEXP);
    Rcpp::traits::input_parameter< String >::type type(typeSEXP);
    Rcpp::traits::input_parameter< int >::type n_paths(n_pathsSEXP);
    Rcpp::traits::input_parameter< int >::type n_steps(n_stepsSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type n_basis(n_basisSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(mc_american_heston_4d(s_0, x_0, k, tau, r_d, r_f, q, kappa_s, theta_s, xi_s, v_s0, kappa_x, theta_x, xi_x, v_x0, rho_sx, rho_sv, rho_xv, rho_svx, rho_xvs, rho_vsvx, type, n_paths, n_steps, seed, n_basis, n_threads));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _LocalVolatility_mc_american_heston_4d(SEXP s_0SEXP, SEXP x_0SEXP, SEXP kSEXP, SEXP tauSEXP, SEXP r_dSEXP, SEXP r_fSEXP, SEXP qSEXP, SEXP kappa_sSEXP, SEXP theta_sSEXP, SEXP xi_sSEXP, SEXP v_s0SEXP, SEXP kappa_xSEXP, SEXP theta_xSEXP, SEXP xi_xSEXP, SEXP v_x0SEXP, SEXP rho_sxSEXP, SEXP rho_svSEXP, SEXP rho_xvSEXP, SEXP rho_svxSEXP, SEXP rho_xvsSEXP, SEXP rho_vsvxSEXP, SEXP typeSEXP, SEXP n_pathsSEXP, SEXP n_stepsSEXP, SEXP seedSEXP, SEXP n_basisSEXP, SEXP n_threadsSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_LocalVolatility_mc_american_heston_4d_try(s_0SEXP, x_0SEXP, kSEXP, tauSEXP, r_dSEXP, r_fSEXP, qSEXP, kappa_sSEXP, theta_sSEXP, xi_sSEXP, v_s0SEXP, kappa_xSEXP, theta_xSEXP, xi_xSEXP, v_x0SEXP, rho_sxSEXP, rho_svSEXP, rho_xvSEXP, rho_svxSEXP, rho_xvsSEXP, rho_vsvxSEXP, typeSEXP, n_pathsSEXP, n_stepsSEXP, seedSEXP, n_basisSEXP, n_threadsSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        (Rf_error)("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// mc_european_heston_4d
Rcpp::List mc_european_heston_4d(double s_0, double x_0, double k, double tau, double r_d, double r_f, double q, double kappa_s, double theta_s, double xi_s, double v_s0, double kappa_x, double theta_x, double xi_x, double v_x0, double rho_sx, double rho_sv, double rho_xv, double rho_svx, double rho_xvs, double rho_vsvx, String type, int n_paths, int n_steps, int seed, int n_threads);
static SEXP _LocalVolatility_mc_european_heston_4d_try(SEXP s_0SEXP, SEXP x_0SEXP, SEXP kSEXP, SEXP tauSEXP, SEXP r_dSEXP, SEXP r_fSEXP, SEXP qSEXP, SEXP kappa_sSEXP, SEXP theta_sSEXP, SEXP xi_sSEXP, SEXP v_s0SEXP, SEXP kappa_xSEXP, SEXP theta_xSEXP, SEXP xi_xSEXP, SEXP v_x0SEXP, SEXP rho_sxSEXP, SEXP rho_svSEXP, SEXP rho_xvSEXP, SEXP rho_svxSEXP, SEXP rho_xvsSEXP, SEXP rho_vsvxSEXP, SEXP typeSEXP, SEXP n_pathsSEXP, SEXP n_stepsSEXP, SEXP seedSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< double >::type s_0(s_0SEXP);
    Rcpp::traits::input_parameter< double >::type x_0(x_0SEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< double >::type r_d(r_dSEXP);
    Rcpp::traits::input_parameter< double >::type r_f(r_fSEXP);
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type kappa_s(kappa_sSEXP);
    Rcpp::traits::input_parameter< double >::type theta_s(theta_sSEXP);
    Rcpp::traits::input_parameter< double >::type xi_s(xi_sSEXP);
    Rcpp::traits::input_parameter< double >::type v_s0(v_s0SEXP);
    Rcpp::traits::input_parameter< double >::type kappa_x(kappa_xSEXP);
    Rcpp::traits::input_parameter< double >::type theta_x(theta_xSEXP);
    Rcpp::traits::input_parameter< double >::type xi_x(xi_xSEXP);
    Rcpp::traits::input_parameter< double >::type v_x0(v_x0SEXP);
    Rcpp::traits::input_parameter< double >::type rho_sx(rho_sxSEXP);
    Rcpp::traits::input_parameter< double >::type rho_sv(rho_svSEXP);
    Rcpp::traits::input_parameter< double >::type rho_xv(rho_xvSEXP);
    Rcpp::traits::input_parameter< double >::type rho_svx(rho_svxSEXP);
    Rcpp::traits::input_parameter< double >::type rho_xvs(rho_xvsSEXP);
    Rcpp::traits::input_parameter< double >::type rho_vsvx(rho_vsvxSEXP);
    Rcpp::traits::input_parameter< String >::type type(typeSEXP);
    Rcpp::traits::input_parameter< int >::type n_paths(n_pathsSEXP);
    Rcpp::traits::input_parameter< int >::type n_steps(n_stepsSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(mc_european_heston_4d(s_0, x_0, k, tau, r_d, r_f, q, kappa_s, theta_s, xi_s, v_s0, kappa_x, theta_x, xi_x, v_x0, rho_sx, rho_sv, rho_xv, rho_svx, rho_xvs, rho_vsvx, type, n_paths, n_steps, seed, n_threads));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _LocalVolatility_mc_european_heston_4d(SEXP s_0SEXP, SEXP x_0SEXP, SEXP kSEXP, SEXP tauSEXP, SEXP r_dSEXP, SEXP r_fSEXP, SEXP qSEXP, SEXP kappa_sSEXP, SEXP theta_sSEXP, SEXP xi_sSEXP, SEXP v_s0SEXP, SEXP kappa_xSEXP, SEXP theta_xSEXP, SEXP xi_xSEXP, SEXP v_x0SEXP, SEXP rho_sxSEXP, SEXP rho_svSEXP, SEXP rho_xvSEXP, SEXP rho_svxSEXP, SEXP rho_xvsSEXP, SEXP rho_vsvxSEXP, SEXP typeSEXP, SEXP n_pathsSEXP, SEXP n_stepsSEXP, SEXP seedSEXP, SEXP n_threadsSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_LocalVolatility_mc_european_heston_4d_try(s_0SEXP, x_0SEXP, kSEXP, tauSEXP, r_dSEXP, r_fSEXP, qSEXP, kappa_sSEXP, theta_sSEXP, xi_sSEXP, v_s0SEXP, kappa_xSEXP, theta_xSEXP, xi_xSEXP, v_x0SEXP, rho_sxSEXP, rho_svSEXP, rho_xvSEXP, rho_svxSEXP, rho_xvsSEXP, rho_vsvxSEXP, typeSEXP, n_pathsSEXP, n_stepsSEXP, seedSEXP, n_threadsSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        (Rf_error)("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// tavella_randall
NumericVector tavella_randall(double x_0, double alpha, double x_min, double x_max, int n_grid);
static SEXP _LocalVolatility_tavella_randall_try(SEXP x_0SEXP, SEXP alphaSEXP, SEXP x_minSEXP, SEXP x_maxSEXP, SEXP n_gridSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< double >::type x_0(x_0SEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type x_min(x_minSEXP);
    Rcpp::traits::input_parameter< double >::type x_max(x_maxSEXP);
    Rcpp::traits::input_parameter< int >::type n_grid(n_gridSEXP);
    rcpp_result_gen = Rcpp::wrap(tavella_randall(x_0, alpha, x_min, x_max, n_grid));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _LocalVolatility_tavella_randall(SEXP x_0SEXP, SEXP alphaSEXP, SEXP x_minSEXP, SEXP x_maxSEXP, SEXP n_gridSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_LocalVolatility_tavella_randall_try(x_0SEXP, alphaSEXP, x_minSEXP, x_maxSEXP, n_gridSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        (Rf_error)("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}

// validate (ensure exported C++ functions exist before calling them)
static int _LocalVolatility_RcppExport_validate(const char* sig) { 
    static std::set<std::string> signatures;
    if (signatures.empty()) {
        signatures.insert("double(*american_option_2d)(double,double,double,double,double,double,double,double,double,double,String,double,double,double,double,int,int,int,double,double,double)");
        signatures.insert("double(*american_option_heston)(double,double,double,double,double,double,double,double,double,double,String,double,double,double,double,int,int,int,double,double,double)");
        signatures.insert("double(*american_option_lv)(double,double,double,double,double,NumericMatrix,String,double,double,int,int,double,double)");
        signatures.insert("double(*american_option_lv_2d)(double,double,double,double,double,double,double,NumericMatrix,NumericMatrix,double,String,double,double,double,double,int,int,int,double,double,double)");
        signatures.insert("Rcpp::NumericVector(*batch_price_european_lv)(const Rcpp::NumericVector&,const Rcpp::NumericVector&,const Rcpp::NumericVector&,const Rcpp::NumericVector&,const Rcpp::NumericVector&,const Rcpp::NumericMatrix&,const Rcpp::StringVector&,double,double,int,int)");
        signatures.insert("Rcpp::NumericVector(*batch_price_american_lv)(const Rcpp::NumericVector&,const Rcpp::NumericVector&,const Rcpp::NumericVector&,const Rcpp::NumericVector&,const Rcpp::NumericVector&,const Rcpp::NumericMatrix&,const Rcpp::StringVector&,double,double,int,int,double,double,int)");
        signatures.insert("double(*european_option_2d)(double,double,double,double,double,double,double,double,double,double,String,double,double,double,double,int,int,int,double)");
        signatures.insert("double(*european_option_cf_2d)(double,double,double,double,double,double,double,double,double,double,String,int)");
        signatures.insert("double(*european_option_heston)(double,double,double,double,double,double,double,double,double,double,String,double,double,double,double,int,int,int,double)");
        signatures.insert("double(*european_option_lv)(double,double,double,double,double,NumericMatrix,String,double,double,int,int)");
        signatures.insert("double(*european_option_lv_2d)(double,double,double,double,double,double,double,NumericMatrix,NumericMatrix,double,String,double,double,double,double,int,int,int,double)");
        signatures.insert("double(*heston_cf)(double,double,double,double,double,double,double,double,double,double,String)");
        signatures.insert("Rcpp::List(*mc_american_heston_4d)(double,double,double,double,double,double,double,double,double,double,double,double,double,double,double,double,double,double,double,double,double,String,int,int,int,int,int)");
        signatures.insert("Rcpp::List(*mc_european_heston_4d)(double,double,double,double,double,double,double,double,double,double,double,double,double,double,double,double,double,double,double,double,double,String,int,int,int,int)");
        signatures.insert("NumericVector(*tavella_randall)(double,double,double,double,int)");
    }
    return signatures.find(sig) != signatures.end();
}

// registerCCallable (register entry points for exported C++ functions)
RcppExport SEXP _LocalVolatility_RcppExport_registerCCallable() { 
    R_RegisterCCallable("LocalVolatility", "_LocalVolatility_american_option_2d", (DL_FUNC)_LocalVolatility_american_option_2d_try);
    R_RegisterCCallable("LocalVolatility", "_LocalVolatility_american_option_heston", (DL_FUNC)_LocalVolatility_american_option_heston_try);
    R_RegisterCCallable("LocalVolatility", "_LocalVolatility_american_option_lv", (DL_FUNC)_LocalVolatility_american_option_lv_try);
    R_RegisterCCallable("LocalVolatility", "_LocalVolatility_american_option_lv_2d", (DL_FUNC)_LocalVolatility_american_option_lv_2d_try);
    R_RegisterCCallable("LocalVolatility", "_LocalVolatility_batch_price_european_lv", (DL_FUNC)_LocalVolatility_batch_price_european_lv_try);
    R_RegisterCCallable("LocalVolatility", "_LocalVolatility_batch_price_american_lv", (DL_FUNC)_LocalVolatility_batch_price_american_lv_try);
    R_RegisterCCallable("LocalVolatility", "_LocalVolatility_european_option_2d", (DL_FUNC)_LocalVolatility_european_option_2d_try);
    R_RegisterCCallable("LocalVolatility", "_LocalVolatility_european_option_cf_2d", (DL_FUNC)_LocalVolatility_european_option_cf_2d_try);
    R_RegisterCCallable("LocalVolatility", "_LocalVolatility_european_option_heston", (DL_FUNC)_LocalVolatility_european_option_heston_try);
    R_RegisterCCallable("LocalVolatility", "_LocalVolatility_european_option_lv", (DL_FUNC)_LocalVolatility_european_option_lv_try);
    R_RegisterCCallable("LocalVolatility", "_LocalVolatility_european_option_lv_2d", (DL_FUNC)_LocalVolatility_european_option_lv_2d_try);
    R_RegisterCCallable("LocalVolatility", "_LocalVolatility_heston_cf", (DL_FUNC)_LocalVolatility_heston_cf_try);
    R_RegisterCCallable("LocalVolatility", "_LocalVolatility_mc_american_heston_4d", (DL_FUNC)_LocalVolatility_mc_american_heston_4d_try);
    R_RegisterCCallable("LocalVolatility", "_LocalVolatility_mc_european_heston_4d", (DL_FUNC)_LocalVolatility_mc_european_heston_4d_try);
    R_RegisterCCallable("LocalVolatility", "_LocalVolatility_tavella_randall", (DL_FUNC)_LocalVolatility_tavella_randall_try);
    R_RegisterCCallable("LocalVolatility", "_LocalVolatility_RcppExport_validate", (DL_FUNC)_LocalVolatility_RcppExport_validate);
    return R_NilValue;
}

static const R_CallMethodDef CallEntries[] = {
    {"_LocalVolatility_american_option_2d", (DL_FUNC) &_LocalVolatility_american_option_2d, 21},
    {"_LocalVolatility_american_option_heston", (DL_FUNC) &_LocalVolatility_american_option_heston, 21},
    {"_LocalVolatility_american_option_lv", (DL_FUNC) &_LocalVolatility_american_option_lv, 13},
    {"_LocalVolatility_american_option_lv_2d", (DL_FUNC) &_LocalVolatility_american_option_lv_2d, 21},
    {"_LocalVolatility_batch_price_european_lv", (DL_FUNC) &_LocalVolatility_batch_price_european_lv, 11},
    {"_LocalVolatility_batch_price_american_lv", (DL_FUNC) &_LocalVolatility_batch_price_american_lv, 14},
    {"_LocalVolatility_european_option_2d", (DL_FUNC) &_LocalVolatility_european_option_2d, 19},
    {"_LocalVolatility_european_option_cf_2d", (DL_FUNC) &_LocalVolatility_european_option_cf_2d, 12},
    {"_LocalVolatility_european_option_heston", (DL_FUNC) &_LocalVolatility_european_option_heston, 19},
    {"_LocalVolatility_european_option_lv", (DL_FUNC) &_LocalVolatility_european_option_lv, 11},
    {"_LocalVolatility_european_option_lv_2d", (DL_FUNC) &_LocalVolatility_european_option_lv_2d, 19},
    {"_LocalVolatility_heston_cf", (DL_FUNC) &_LocalVolatility_heston_cf, 11},
    {"_LocalVolatility_mc_american_heston_4d", (DL_FUNC) &_LocalVolatility_mc_american_heston_4d, 27},
    {"_LocalVolatility_mc_european_heston_4d", (DL_FUNC) &_LocalVolatility_mc_european_heston_4d, 26},
    {"_LocalVolatility_tavella_randall", (DL_FUNC) &_LocalVolatility_tavella_randall, 5},
    {"_LocalVolatility_RcppExport_registerCCallable", (DL_FUNC) &_LocalVolatility_RcppExport_registerCCallable, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_LocalVolatility(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
