# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' American Option 1D (local volatility, penalty method)
#'
#' Prices an American option on a single equity with local volatility using operator splitting
#' and a penalty-projection method for the early exercise constraint.
#'
#' @param s_0 Stock spot price.
#' @param k Strike price.
#' @param tau Time to expiry (in years).
#' @param r_d Risk-free rate (domestic).
#' @param q Dividend yield.
#' @param sigma Local volatility matrix sampled on the grid.
#' @param type Either "call" or "put".
#' @param s_min,s_max Min/Max of the underlying prices grid.
#' @param n_s Number of intervals in the asset grid (n_s + 1 nodes).
#' @param n_t Number of time steps.
#' @param lambda Penalty parameter (> 1).
#' @param tolerance Relative error tolerance for the penalty iterations.
#'
#' @export
american_option_lv <- function(s_0, k, tau, r_d, q, sigma, type, s_min, s_max, n_s, n_t, lambda, tolerance) {
    .Call(`_LocalVolatility_american_option_lv`, s_0, k, tau, r_d, q, sigma, type, s_min, s_max, n_s, n_t, lambda, tolerance)
}

#' European Option 1D (local volatility)
#'
#' Prices a European option on a single equity with local volatility using a 1D Crank–Nicolson
#' finite-difference scheme, time-dependent boundaries, and linear interpolation at the spot.
#'
#' @param s_0 Stock spot price.
#' @param k Strike price.
#' @param tau Time to expiry (in years).
#' @param r_d Risk-free rate (domestic).
#' @param q Dividend yield.
#' @param sigma Local volatility matrix sampled on the grid; commonly (n_s + 1) x (n_t + 1) or
#'   (n_s + 1) x n_t depending on solver indexing.
#' @param type Either "call" or "put".
#' @param s_min,s_max Min/Max of the asset grid.
#' @param n_s Number of intervals in the asset grid (n_s + 1 nodes).
#' @param n_t Number of time steps.
#'
#' @export
european_option_lv <- function(s_0, k, tau, r_d, q, sigma, type, s_min, s_max, n_s, n_t) {
    .Call(`_LocalVolatility_european_option_lv`, s_0, k, tau, r_d, q, sigma, type, s_min, s_max, n_s, n_t)
}

#' American Option 2D (local volatility, penalty method)
#'
#' Prices an American option on an equity in a foreign currency with local volatilities for both S and X.
#' Uses operator splitting and a penalty-projection scheme for the obstacle.
#'
#' @param s_0 Stock spot price.
#' @param x_0 FX spot price (domestic per foreign).
#' @param k Strike price (domestic currency).
#' @param tau Time to expiry (in years).
#' @param r_d Risk-free rate (domestic).
#' @param r_f Risk-free rate (foreign).
#' @param q Dividend yield.
#' @param sigma_s Local volatility matrix for the stock of size (n_s + 1) x n_t.
#' @param sigma_x Local volatility matrix for the FX of size (n_x + 1) x n_t.
#' @param rho Correlation between the stock and the FX in `[-1, 1]`.
#' @param type Either "call" or "put".
#' @param s_min,s_max Min/Max of the stock grid.
#' @param x_min,x_max Min/Max of the FX grid.
#' @param n_s Number of intervals in stock grid (n_s + 1 nodes).
#' @param n_x Number of intervals in FX grid (n_x + 1 nodes).
#' @param n_t Number of time steps.
#' @param alpha Grid clustering parameter for Tavella–Randall grids (> 0).
#' @param lambda Penalty parameter (> 1).
#' @param tolerance Relative error tolerance for the penalty fixed-point iterations.
#'
#' @details
#' Domestic-measure drift and discounting as in the constant-vol case, using local pointwise vols:
#' mu_S = r_f - q - rho * sigma_S * sigma_X in S, r_d - r_f in X, discounting at r_d. Far-field
#' boundaries use exp(-q * tau) on S·X and exp(-r_d * tau) on K.
#'
#' @export
american_option_lv_2d <- function(s_0, x_0, k, tau, r_d, r_f, q, sigma_s, sigma_x, rho, type, s_min, s_max, x_min, x_max, n_s, n_x, n_t, alpha, lambda, tolerance) {
    .Call(`_LocalVolatility_american_option_lv_2d`, s_0, x_0, k, tau, r_d, r_f, q, sigma_s, sigma_x, rho, type, s_min, s_max, x_min, x_max, n_s, n_x, n_t, alpha, lambda, tolerance)
}

#' American Option 2D (constant volatility, penalty method)
#'
#' Prices an American option on an equity quoted in a foreign currency using a 2D finite-difference PDE
#' with Yanenko operator splitting and a penalty-projection scheme for the early exercise constraint.
#'
#' @param s_0 Stock spot price.
#' @param x_0 FX spot price (domestic per foreign).
#' @param k Strike price (domestic currency).
#' @param tau Time to expiry (in years).
#' @param r_d Risk-free rate (domestic).
#' @param r_f Risk-free rate (foreign).
#' @param q Dividend yield.
#' @param sigma_s Constant volatility of the stock.
#' @param sigma_x Constant volatility of the FX.
#' @param rho Correlation between the stock and the FX in `[-1, 1]`.
#' @param type Either "call" or "put".
#' @param s_min,s_max Min/Max of the stock grid.
#' @param x_min,x_max Min/Max of the FX grid.
#' @param n_s Number of intervals in stock grid (n_s + 1 nodes).
#' @param n_x Number of intervals in FX grid (n_x + 1 nodes).
#' @param n_t Number of time steps.
#' @param alpha Grid clustering parameter for Tavella–Randall grids (> 0).
#' @param lambda Penalty parameter (> 1).
#' @param tolerance Relative error tolerance for the penalty fixed-point iterations.
#'
#' @details
#' Domestic-measure drift and discounting are applied (mu_S = r_f - q - rho * sigma_s * sigma_x in S,
#' r_d - r_f in X, discounting at r_d). Far-field Dirichlet boundaries use exp(-q * tau) on S·X and
#' exp(-r_d * tau) on K. The penalty parameter is split across the two sub-steps.
#'
american_option_2d <- function(s_0, x_0, k, tau, r_d, r_f, q, sigma_s, sigma_x, rho, type, s_min, s_max, x_min, x_max, n_s, n_x, n_t, alpha, lambda, tolerance) {
    .Call(`_LocalVolatility_american_option_2d`, s_0, x_0, k, tau, r_d, r_f, q, sigma_s, sigma_x, rho, type, s_min, s_max, x_min, x_max, n_s, n_x, n_t, alpha, lambda, tolerance)
}

#' European Option 2D (local volatility)
#'
#' Prices a European option on an equity in a foreign currency using a 2D finite-difference PDE
#' with time- and state-dependent local volatilities for both S and X.
#'
#' @param s_0 Stock spot price.
#' @param x_0 FX spot price (domestic per foreign).
#' @param k Strike price (domestic currency).
#' @param tau Time to expiry (in years).
#' @param r_d Risk-free rate (domestic).
#' @param r_f Risk-free rate (foreign).
#' @param q Dividend yield.
#' @param sigma_s Local volatility matrix for the stock of size (n_s + 1) x n_t.
#' @param sigma_x Local volatility matrix for the FX of size (n_x + 1) x n_t.
#' @param rho Correlation between the stock and the FX in `[-1, 1]`.
#' @param type Either "call" or "put".
#' @param s_min,s_max Min/Max of the stock grid.
#' @param x_min,x_max Min/Max of the FX grid.
#' @param n_s Number of intervals in stock grid (n_s + 1 nodes).
#' @param n_x Number of intervals in FX grid (n_x + 1 nodes).
#' @param n_t Number of time steps.
#' @param alpha Grid clustering parameter for Tavella–Randall grids (> 0).
#'
#' @details
#' Domestic-measure drift and discounting are applied as in the constant-vol solver, but with
#' pointwise volatilities. In the S-direction, mu_S = r_f - q - rho * sigma_S * sigma_X (local).
#' In the X-direction, drift is r_d - r_f. Far-field Dirichlet boundaries use exp(-q * tau) on S·X
#' and exp(-r_d * tau) on K. When `sigma_s` and `sigma_x` are constant-valued matrices, prices
#' should match the constant-vol solver up to numerical tolerance.
#'
#' @export
european_option_lv_2d <- function(s_0, x_0, k, tau, r_d, r_f, q, sigma_s, sigma_x, rho, type, s_min, s_max, x_min, x_max, n_s, n_x, n_t, alpha) {
    .Call(`_LocalVolatility_european_option_lv_2d`, s_0, x_0, k, tau, r_d, r_f, q, sigma_s, sigma_x, rho, type, s_min, s_max, x_min, x_max, n_s, n_x, n_t, alpha)
}

#' European Option 2D (constant volatility)
#'
#' Prices a European option on an equity quoted in a foreign currency using a 2D finite-difference PDE
#' with Yanenko operator splitting, constant volatilities (sigma_s, sigma_x), and a centered mixed-derivative.
#'
#' @param s_0 Stock spot price.
#' @param x_0 FX spot price (domestic per foreign).
#' @param k Strike price (domestic currency).
#' @param tau Time to expiry (in years).
#' @param r_d Risk-free rate (domestic).
#' @param r_f Risk-free rate (foreign).
#' @param q Dividend yield.
#' @param sigma_s Constant volatility of the stock.
#' @param sigma_x Constant volatility of the FX.
#' @param rho Correlation between the stock and the FX in `[-1, 1]`.
#' @param type Either "call" or "put".
#' @param s_min,s_max Min/Max of the stock grid.
#' @param x_min,x_max Min/Max of the FX grid.
#' @param n_s Number of intervals in stock grid (n_s + 1 nodes).
#' @param n_x Number of intervals in FX grid (n_x + 1 nodes).
#' @param n_t Number of time steps.
#' @param alpha Grid clustering parameter for Tavella–Randall grids (> 0).
#'
#' @details
#' Domestic-measure drift and discounting are applied. In the S-direction, the drift is
#' mu_S = r_f - q - rho * sigma_s * sigma_x. In the X-direction, the drift is r_d - r_f, and
#' discounting is at r_d. Far-field Dirichlet boundaries use exp(-q * tau) on the S·X term and
#' exp(-r_d * tau) on K. The spot (s_0, x_0) price is obtained via bilinear interpolation.
#'
#' @export
european_option_2d <- function(s_0, x_0, k, tau, r_d, r_f, q, sigma_s, sigma_x, rho, type, s_min, s_max, x_min, x_max, n_s, n_x, n_t, alpha) {
    .Call(`_LocalVolatility_european_option_2d`, s_0, x_0, k, tau, r_d, r_f, q, sigma_s, sigma_x, rho, type, s_min, s_max, x_min, x_max, n_s, n_x, n_t, alpha)
}

#' Generate a sequence based on the Tavella and Randall method
#'
#' This function generates a sequence of numbers following the Tavella and Randall method,
#' which applies a combination of hyperbolic sine transformations to create a smooth sequence
#' between a specified minimum and maximum value.
#'
#' @param x0 Numeric. The central value around which the sequence is generated.
#' @param alpha Numeric. A scaling parameter that controls the shape of the sequence.
#' @param x_min Numeric. The minimum value of the sequence.
#' @param x_max Numeric. The maximum value of the sequence.
#' @param n Integer. The number of values in the generated sequence.
#'
#' @return A numeric vector of length `n` containing the generated sequence.
#'
#' @details The function calculates the sequence by dividing the interval `[0, 1]` into `n`
#' equally spaced points. At each point, it computes the corresponding value based on the
#' Tavella and Randall method, which uses the hyperbolic sine function to ensure a smooth
#' transition between `x_min` and `x_max`.
#'
#' @export
tavella_randall <- function(x0, alpha, x_min, x_max, n) {
    .Call(`_LocalVolatility_tavella_randall`, x0, alpha, x_min, x_max, n)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call(`_LocalVolatility_RcppExport_registerCCallable`)
})
