# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' American Option 2D (constant volatility, penalty method)
#'
#' Prices an American option on an equity quoted in a foreign currency using a
#' 2D finite-difference PDE with Yanenko operator splitting and a
#' penalty-projection scheme for the early exercise constraint.
#'
#' @param s_0 Stock spot price.
#' @param x_0 FX spot price (domestic per foreign).
#' @param k Strike price (domestic currency).
#' @param tau Time to expiry (in years).
#' @param r_d Risk-free rate (domestic).
#' @param r_f Risk-free rate (foreign).
#' @param q Dividend yield.
#' @param sigma_s Constant volatility of the stock (>= 0).
#' @param sigma_x Constant volatility of the FX (>= 0).
#' @param rho Correlation between the stock and the FX in \code{[-1, 1]}.
#' @param type Either \code{"call"} or \code{"put"}.
#' @param s_min,s_max Min/Max of the stock grid.
#' @param x_min,x_max Min/Max of the FX grid.
#' @param n_s Number of intervals in stock grid (\code{n_s + 1} nodes).
#' @param n_x Number of intervals in FX grid (\code{n_x + 1} nodes).
#' @param n_t Number of time steps.
#' @param alpha Grid clustering parameter for Tavella-Randall grids (> 0).
#' @param lambda Penalty parameter (> 0, typically 1e4 to 1e6).
#' @param tolerance Convergence tolerance for penalty iterations.
#'
#' @return Option price as a numeric scalar.
#'
#' @details
#' Domestic-measure dynamics: drift \eqn{\mu_S = r_f - q - \rho \sigma_S \sigma_X}
#' in S, \eqn{r_d - r_f} in X, discounting at \eqn{r_d}. The penalty parameter
#' is split as \eqn{\lambda/2} across the two operator-splitting sub-steps.
#' Maximum 200 penalty iterations per time step with a warning on non-convergence.
#'
#' @export
american_option_2d <- function(s_0, x_0, k, tau, r_d, r_f, q, sigma_s, sigma_x, rho, type, s_min, s_max, x_min, x_max, n_s, n_x, n_t, alpha, lambda, tolerance) {
    .Call(`_LocalVolatility_american_option_2d`, s_0, x_0, k, tau, r_d, r_f, q, sigma_s, sigma_x, rho, type, s_min, s_max, x_min, x_max, n_s, n_x, n_t, alpha, lambda, tolerance)
}

#' American Option 1D (local volatility, penalty method)
#'
#' Prices an American option on a single equity with local volatility using
#' Crank-Nicolson finite differences and a penalty-projection method for the
#' early exercise constraint.
#'
#' @param s_0 Stock spot price.
#' @param k Strike price.
#' @param tau Time to expiry (in years).
#' @param r_d Risk-free rate (domestic).
#' @param r_f Foreign risk-free rate or cost-of-carry rate (e.g. dividend yield).
#' @param sigma Local volatility matrix of size \code{(n_s + 1) x (n_t + 1)},
#'   sampled on the spatial grid (rows) and time grid including both endpoints (columns).
#' @param type Either \code{"call"} or \code{"put"}.
#' @param s_min,s_max Min/Max of the underlying prices grid.
#' @param n_s Number of intervals in the asset grid (\code{n_s + 1} nodes).
#' @param n_t Number of time steps.
#' @param lambda Penalty parameter (> 0, typically 1e4 to 1e6).
#' @param tolerance Convergence tolerance for penalty iterations.
#'
#' @return Option price as a numeric scalar.
#'
#' @details
#' The solver uses the standard Black-Scholes PDE with time- and state-dependent
#' volatility \eqn{\sigma(S, t)}, discretised via Crank-Nicolson. The early exercise
#' constraint is enforced through a penalty-projection fixed-point iteration at each
#' time step, with a maximum of 200 iterations and a warning on non-convergence.
#'
#' @export
american_option_lv <- function(s_0, k, tau, r_d, r_f, sigma, type, s_min, s_max, n_s, n_t, lambda, tolerance) {
    .Call(`_LocalVolatility_american_option_lv`, s_0, k, tau, r_d, r_f, sigma, type, s_min, s_max, n_s, n_t, lambda, tolerance)
}

#' American Option 2D (local volatility, penalty method)
#'
#' Prices an American option on an equity in a foreign currency with local
#' volatilities for both S and X, using Yanenko operator splitting and a
#' penalty-projection scheme for the early exercise constraint on a
#' non-uniform Tavella-Randall grid.
#'
#' @param s_0 Stock spot price.
#' @param x_0 FX spot price (domestic per foreign).
#' @param k Strike price (domestic currency).
#' @param tau Time to expiry (in years).
#' @param r_d Risk-free rate (domestic).
#' @param r_f Risk-free rate (foreign).
#' @param q Dividend yield.
#' @param sigma_s Local volatility matrix for the stock of size \code{(n_s + 1) x n_t}.
#' @param sigma_x Local volatility matrix for the FX of size \code{(n_x + 1) x n_t}.
#' @param rho Correlation between the stock and the FX in \code{[-1, 1]}.
#' @param type Either \code{"call"} or \code{"put"}.
#' @param s_min,s_max Min/Max of the stock grid.
#' @param x_min,x_max Min/Max of the FX grid.
#' @param n_s Number of intervals in stock grid (\code{n_s + 1} nodes).
#' @param n_x Number of intervals in FX grid (\code{n_x + 1} nodes).
#' @param n_t Number of time steps.
#' @param alpha Grid clustering parameter for Tavella-Randall grids (> 0).
#' @param lambda Penalty parameter (> 0, typically 1e4 to 1e6).
#' @param tolerance Convergence tolerance for penalty iterations.
#'
#' @return Option price as a numeric scalar.
#'
#' @details
#' Domestic-measure dynamics with pointwise volatilities:
#' \eqn{\mu_S = r_f - q - \rho \sigma_S \sigma_X} in S, \eqn{r_d - r_f} in X,
#' discounting at \eqn{r_d}. The penalty parameter is split as \eqn{\lambda/2}
#' across the two operator-splitting sub-steps. Maximum 200 penalty iterations
#' per time step with a warning on non-convergence.
#'
#' @export
american_option_lv_2d <- function(s_0, x_0, k, tau, r_d, r_f, q, sigma_s, sigma_x, rho, type, s_min, s_max, x_min, x_max, n_s, n_x, n_t, alpha, lambda, tolerance) {
    .Call(`_LocalVolatility_american_option_lv_2d`, s_0, x_0, k, tau, r_d, r_f, q, sigma_s, sigma_x, rho, type, s_min, s_max, x_min, x_max, n_s, n_x, n_t, alpha, lambda, tolerance)
}

#' Batch-price European options under local volatility (1D)
#'
#' Prices multiple European options that share the same local volatility surface
#' and PDE grid in a single backward Crank-Nicolson sweep. Much faster than
#' calling \code{\link{european_option_lv}} in a loop because the tridiagonal
#' LHS is factored once per time step and reused across all options.
#'
#' @param spots Numeric vector of spot prices (one per option).
#' @param strikes Numeric vector of strike prices.
#' @param taus Numeric vector of times to expiry (years).
#' @param r_ds Numeric vector of domestic risk-free rates.
#' @param r_fs Numeric vector of foreign risk-free rates or cost-of-carry rates.
#' @param sigma Local volatility matrix of size \code{(n_s + 1) x (n_t + 1)}.
#' @param types Character vector, each element \code{"call"} or \code{"put"}.
#' @param s_min,s_max Domain bounds for the asset grid.
#' @param n_s Number of spatial intervals (\code{n_s + 1} nodes).
#' @param n_t Number of time steps.
#'
#' @return Numeric vector of option prices (same length as \code{strikes}).
#'
#' @details
#' All options must lie on the same spatial domain \code{[s_min, s_max]} and
#' use the same sigma surface. The solver steps backward from \code{max(taus)}
#' and extracts each option's price at the time step closest to its maturity.
#' The tridiagonal Crank-Nicolson system is factored once per time step (the
#' LHS depends only on sigma and the grid, not on the strike), and each
#' option's RHS is solved via forward/back substitution — O(n_s) per option
#' per time step instead of O(2 * n_s) for a full Thomas solve.
#'
#' @export
batch_price_european_lv <- function(spots, strikes, taus, r_ds, r_fs, sigma, types, s_min, s_max, n_s, n_t) {
    .Call(`_LocalVolatility_batch_price_european_lv`, spots, strikes, taus, r_ds, r_fs, sigma, types, s_min, s_max, n_s, n_t)
}

#' Batch-price American options under local volatility (1D)
#'
#' Prices multiple American options that share the same local volatility surface
#' and PDE grid. Each option is an independent backward Crank-Nicolson solve
#' with penalty-projection for early exercise, parallelized across options
#' via OpenMP.
#'
#' @param spots Numeric vector of spot prices (one per option).
#' @param strikes Numeric vector of strike prices.
#' @param taus Numeric vector of times to expiry (years).
#' @param r_ds Numeric vector of domestic risk-free rates.
#' @param r_fs Numeric vector of foreign risk-free rates or cost-of-carry rates.
#' @param sigma Local volatility matrix of size \code{(n_s + 1) x (n_t + 1)}.
#' @param types Character vector, each element \code{"call"} or \code{"put"}.
#' @param s_min,s_max Domain bounds for the asset grid.
#' @param n_s Number of spatial intervals (\code{n_s + 1} nodes).
#' @param n_t Number of time steps.
#' @param lambda Penalty parameter (> 0, typically 1e4 to 1e6).
#' @param tolerance Convergence tolerance for penalty iterations.
#'
#' @return Numeric vector of option prices (same length as \code{strikes}).
#'
#' @details
#' Each option is solved independently using the same sigma surface and grid.
#' The solver uses Crank-Nicolson with a penalty-projection fixed-point
#' iteration for the American constraint, capped at 200 iterations per time
#' step. Options are solved in parallel across CPU cores using std::thread.
#'
#' @export
batch_price_american_lv <- function(spots, strikes, taus, r_ds, r_fs, sigma, types, s_min, s_max, n_s, n_t, lambda, tolerance) {
    .Call(`_LocalVolatility_batch_price_american_lv`, spots, strikes, taus, r_ds, r_fs, sigma, types, s_min, s_max, n_s, n_t, lambda, tolerance)
}

#' European Option 2D (constant volatility)
#'
#' Prices a European option on an equity quoted in a foreign currency using a
#' 2D finite-difference PDE with Yanenko operator splitting, constant
#' volatilities, and a centered mixed-derivative stencil on a non-uniform
#' Tavella-Randall grid.
#'
#' @param s_0 Stock spot price.
#' @param x_0 FX spot price (domestic per foreign).
#' @param k Strike price (domestic currency).
#' @param tau Time to expiry (in years).
#' @param r_d Risk-free rate (domestic).
#' @param r_f Risk-free rate (foreign).
#' @param q Dividend yield.
#' @param sigma_s Constant volatility of the stock (>= 0).
#' @param sigma_x Constant volatility of the FX (>= 0).
#' @param rho Correlation between the stock and the FX in \code{[-1, 1]}.
#' @param type Either \code{"call"} or \code{"put"}.
#' @param s_min,s_max Min/Max of the stock grid.
#' @param x_min,x_max Min/Max of the FX grid.
#' @param n_s Number of intervals in stock grid (\code{n_s + 1} nodes).
#' @param n_x Number of intervals in FX grid (\code{n_x + 1} nodes).
#' @param n_t Number of time steps.
#' @param alpha Grid clustering parameter for Tavella-Randall grids (> 0).
#'
#' @return Option price as a numeric scalar.
#'
#' @details
#' Domestic-measure dynamics: drift \eqn{\mu_S = r_f - q - \rho \sigma_S \sigma_X}
#' in S, \eqn{r_d - r_f} in X, discounting at \eqn{r_d}. Far-field Dirichlet
#' boundaries use \eqn{e^{-(r_f + q)\tau}} on the \eqn{S \cdot X} leg and
#' \eqn{e^{-r_d \tau}} on \eqn{K}.
#'
#' @export
european_option_2d <- function(s_0, x_0, k, tau, r_d, r_f, q, sigma_s, sigma_x, rho, type, s_min, s_max, x_min, x_max, n_s, n_x, n_t, alpha) {
    .Call(`_LocalVolatility_european_option_2d`, s_0, x_0, k, tau, r_d, r_f, q, sigma_s, sigma_x, rho, type, s_min, s_max, x_min, x_max, n_s, n_x, n_t, alpha)
}

#' European Option 2D (closed-form, ADR)
#'
#' Closed-form Black-Scholes price for a European option on an ADR whose
#' underlying is the product S*X scaled by the ADR ratio: ADR = (S*X)/adr_ratio.
#' Assumes constant volatilities for S and X and correlation rho. The
#' effective ADR log-volatility is
#'   sigma_adr = sqrt(sigma_s^2 + sigma_x^2 + 2 * rho * sigma_s * sigma_x).
#'
#' The domestic-measure discounting is used: SX leg discounted by exp(-q * tau),
#' strike leg by exp(-r_d * tau). Note r_f does not enter the closed form directly
#' but is kept for API symmetry with PDE solvers.
#'
#' @param s_0 Stock spot price S(0).
#' @param x_0 FX spot price X(0) (domestic per foreign).
#' @param k Strike price (domestic currency).
#' @param tau Time to expiry (in years, > 0).
#' @param r_d Risk-free rate (domestic).
#' @param r_f Risk-free rate (foreign) — kept for signature symmetry.
#' @param q Dividend yield for the equity.
#' @param sigma_s Constant volatility of the stock.
#' @param sigma_x Constant volatility of the FX.
#' @param rho Correlation between the stock and the FX in \code{[-1, 1]}.
#' @param type Either \code{"call"} or \code{"put"}.
#' @param adr_ratio ADR ratio (shares per ADR), usually >= 1.
#'
#' @return Option price as a numeric scalar.
#'
#' @details
#' This is the standard Black-Scholes formula applied to ADR = (S*X)/adr_ratio with
#' log-normal dynamics under the domestic measure. Let ADR_0 = (s_0 * x_0)/adr_ratio and
#' sigma_adr as above. Then
#'   \code{d1 = [ln(ADR_0 / K) + (r_d - q + 0.5 * sigma_adr^2) * tau] / (sigma_adr * sqrt(tau))},
#'   \code{d2 = d1 - sigma_adr * sqrt(tau)}.
#' The call is \code{ADR_0 * exp(-q*tau) * N(d1) - K * exp(-r_d*tau) * N(d2)}; the put uses put-call parity.
#'
#' @examples
#' european_option_cf_2d(100, 20, 2000, 1, 0.05, 0.02, 0.01, 0.2, 0.1, 0.3, "call", 1)
#'
#' @export
european_option_cf_2d <- function(s_0, x_0, k, tau, r_d, r_f, q, sigma_s, sigma_x, rho, type, adr_ratio) {
    .Call(`_LocalVolatility_european_option_cf_2d`, s_0, x_0, k, tau, r_d, r_f, q, sigma_s, sigma_x, rho, type, adr_ratio)
}

#' European Option 1D (local volatility)
#'
#' Prices a European option on a single equity with local volatility using a
#' 1D Crank-Nicolson finite-difference scheme, time-dependent Dirichlet
#' boundaries, and linear interpolation at the spot.
#'
#' @param s_0 Stock spot price.
#' @param k Strike price.
#' @param tau Time to expiry (in years).
#' @param r_d Risk-free rate (domestic).
#' @param r_f Foreign risk-free rate or cost-of-carry rate (e.g. dividend yield).
#' @param sigma Local volatility matrix of size \code{(n_s + 1) x (n_t + 1)},
#'   sampled on the spatial grid (rows) and time grid including both endpoints (columns).
#' @param type Either \code{"call"} or \code{"put"}.
#' @param s_min,s_max Min/Max of the asset grid.
#' @param n_s Number of intervals in the asset grid (\code{n_s + 1} nodes).
#' @param n_t Number of time steps.
#'
#' @return Option price as a numeric scalar.
#'
#' @export
european_option_lv <- function(s_0, k, tau, r_d, r_f, sigma, type, s_min, s_max, n_s, n_t) {
    .Call(`_LocalVolatility_european_option_lv`, s_0, k, tau, r_d, r_f, sigma, type, s_min, s_max, n_s, n_t)
}

#' European Option 2D (local volatility)
#'
#' Prices a European option on an equity in a foreign currency using a 2D
#' finite-difference PDE with time- and state-dependent local volatilities
#' for both S and X, Yanenko operator splitting, and a centered mixed-derivative
#' stencil on a non-uniform Tavella-Randall grid.
#'
#' @param s_0 Stock spot price.
#' @param x_0 FX spot price (domestic per foreign).
#' @param k Strike price (domestic currency).
#' @param tau Time to expiry (in years).
#' @param r_d Risk-free rate (domestic).
#' @param r_f Risk-free rate (foreign).
#' @param q Dividend yield.
#' @param sigma_s Local volatility matrix for the stock of size \code{(n_s + 1) x n_t}.
#' @param sigma_x Local volatility matrix for the FX of size \code{(n_x + 1) x n_t}.
#' @param rho Correlation between the stock and the FX in \code{[-1, 1]}.
#' @param type Either \code{"call"} or \code{"put"}.
#' @param s_min,s_max Min/Max of the stock grid.
#' @param x_min,x_max Min/Max of the FX grid.
#' @param n_s Number of intervals in stock grid (\code{n_s + 1} nodes).
#' @param n_x Number of intervals in FX grid (\code{n_x + 1} nodes).
#' @param n_t Number of time steps.
#' @param alpha Grid clustering parameter for Tavella-Randall grids (> 0).
#'
#' @return Option price as a numeric scalar.
#'
#' @details
#' Domestic-measure dynamics with pointwise volatilities:
#' \eqn{\mu_S = r_f - q - \rho \sigma_S \sigma_X} in S, \eqn{r_d - r_f} in X,
#' discounting at \eqn{r_d}. When \code{sigma_s} and \code{sigma_x} are
#' constant-valued matrices, prices match the constant-vol solver to numerical
#' tolerance.
#'
#' @export
european_option_lv_2d <- function(s_0, x_0, k, tau, r_d, r_f, q, sigma_s, sigma_x, rho, type, s_min, s_max, x_min, x_max, n_s, n_x, n_t, alpha) {
    .Call(`_LocalVolatility_european_option_lv_2d`, s_0, x_0, k, tau, r_d, r_f, q, sigma_s, sigma_x, rho, type, s_min, s_max, x_min, x_max, n_s, n_x, n_t, alpha)
}

#' Generate a sequence based on the Tavella and Randall method
#'
#' This function generates a sequence of numbers following the Tavella and Randall method,
#' which applies a combination of hyperbolic sine transformations to create a smooth sequence
#' between a specified minimum and maximum value.
#'
#' @param x_0 Numeric. The central value around which the sequence is generated.
#' @param alpha Numeric. A scaling parameter that controls the shape of the sequence.
#' @param x_min Numeric. The minimum value of the sequence.
#' @param x_max Numeric. The maximum value of the sequence.
#' @param n_grid Integer. The number of intervals in the generated sequence
#'   (\code{n_grid + 1} nodes).
#'
#' @return A numeric vector of length \code{n_grid + 1} containing the generated sequence.
#'
#' @details The function divides the interval \code{[0, 1]} into \code{n_grid}
#' equally spaced points. At each point, it computes the corresponding value based on the
#' Tavella and Randall method, which uses the hyperbolic sine function to ensure a smooth
#' transition between \code{x_min} and \code{x_max}.
#'
#' @export
tavella_randall <- function(x_0, alpha, x_min, x_max, n_grid) {
    .Call(`_LocalVolatility_tavella_randall`, x_0, alpha, x_min, x_max, n_grid)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call(`_LocalVolatility_RcppExport_registerCCallable`)
})
